### ISSUE TITLE
how to get scStereo-seq data

### ISSUE THREAD

**Issue by sarahshuang** [yangmean/Spatiotemperal_mouse_implation_sites#1]
Hi,

I cannot find scStereo-seq data directly on the website ( https://meissta.com/ ) where only shows the interactive data portal. Could you please tell me how to get scStereo-seq data?

**Comment by yangmean** [comment]
Hi Sarah, 
The processed data (.RData) is available on the website, and you can obtain it by clicking the "Download" button for each stereo-seq slide data. Additionally, I will soon organize the spatial data into the database to address the issue.

**Comment by sarahshuang** [comment]
> Hi Sarah, The processed data (.RData) is available on the website, and you can obtain it by clicking the "Download" button for each stereo-seq slide data. Additionally, I will soon organize the spatial data into the database to address the issue.

Oh! Great. Big thanks!! =]

**Comment by sarahshuang** [comment]
Hi,

I am doing further analysis based on your stereo-seq data. For the visualization of the processed data E8.5-1 (B6.bin50_diet.rds), there are a few blank spots between each cell type which confuses me. I am wondering whether I can get access to the raw data or know the preprocessing of the data.  =]

**Comment by liuyifang** [comment]
Hi Yang,

Your website takes pretty long time to load, can you provide other ways to download the scStereo-seq data, either GEO or other data hub. Thanks!

**Comment by yangmean** [comment]
> confuses

Hello, apologies for the delayed response. I believe the blank spots are attributed to tissue composition. Certain tissues may exhibit some areas with blank spots.

**Comment by yangmean** [comment]
> Hi Yang,
> 
> Your website takes pretty long time to load, can you provide other ways to download the scStereo-seq data, either GEO or other data hub. Thanks!


I plan to submit the data to GEO, but the raw data is quite large, so the process might take a considerable amount of time.

**Comment by liuyifang** [comment]
> > Hi Yang,
> > Your website takes pretty long time to load, can you provide other ways to download the scStereo-seq data, either GEO or other data hub. Thanks!
> 
> I plan to submit the data to GEO, but the raw data is quite large, so the process might take a considerable amount of time.

Thank you, can you estimate a rough time for when the data upload will be completed?

**Comment by yangmean** [comment]
@liuyifang I transferred the data to the SRA database yesterday, but the raw FASTQ data exceeds 1 terabyte. Therefore, the upload process may take more than one day. Once completed, I will update the accession number. I am so sorry for the inconvenience.

**Comment by liuyifang** [comment]
@yangmean I have problem download the scStereo-seq E9.5 rds file from the meissta website. When you upload the processed data to GEO, can you also keep the raw counts and meta data in the seurat object. This info is important to integrate with my data. Thanks!

**Comment by sarahshuang** [comment]
> > confuses
> 
> Hello, apologies for the delayed response. I believe the blank spots are attributed to tissue composition. Certain tissues may exhibit some areas with blank spots.

Yep. That's the point that I am confused. According to Fig.3A (the H&E image), it seems that it is supposed to have more blank spots, especially for matured DSC for E8.5, but it is fully annotated. Therefore I wonder the reason behind it. It is more similar to 10X data rather than stereo-seq. Did you fill in the blank or do some preprocess?
<img width="1173" alt="截屏2023-11-27 08 46 35" src="https://github.com/yangmean/Spatiotemporal_mouse_implantation_sites/assets/105658106/683db73b-59af-42fc-9973-3a469f791a26">

**Comment by yangmean** [comment]
@sarahshuang Hi, The H&E staining in Figure 3A does not correspond to the same or closely related tissue slide as the stereo-seq data in Figure 3B. The consistent H&E staining for Figure 3B is shown in Figure S2A.

**Comment by yangmean** [comment]
> @yangmean I have problem download the scStereo-seq E9.5 rds file from the meissta website. When you upload the processed data to GEO, can you also keep the raw counts and meta data in the seurat object. This info is important to integrate with my data. Thanks!


I keep it in the Seurat object, and I'm also uploading the processed .gem file.

**Comment by sarahshuang** [comment]
> @sarahshuang Hi, The H&E staining in Figure 3A does not correspond to the same or closely related tissue slide as the stereo-seq data in Figure 3B. The consistent H&E staining for Figure 3B is shown in Figure S2A.

Ohhh!Thanks! I did not note it in Figure S2. That is my fault. So maybe one more question, how can I get access to such an H&E image in a higher resolution? I want to compare the H&E image and cell type annotation to deeply analyze it.

**Comment by yangmean** [comment]
@sarahshuang I had initially intended to pursue the same approach. However, I discovered that the H&E staining on the Stereo-seq tissues was not satisfactory. Consequently, we switched to alternative tissues with the same embryonic development time. For the stereo-seq tissues, I only got the high-resolution of ssDNA image from BGI.

**Comment by sarahshuang** [comment]
> @sarahshuang I had initially intended to pursue the same approach. However, I discovered that the H&E staining on the Stereo-seq tissues was not satisfactory. Consequently, we switched to alternative tissues with the same embryonic development time. For the stereo-seq tissues, I only got the high-resolution of ssDNA image from BGI.

However, can I get the access to the original H&E image not the one with high resolution?

**Comment by liuyifang** [comment]
> > @yangmean I have problem download the scStereo-seq E9.5 rds file from the meissta website. When you upload the processed data to GEO, can you also keep the raw counts and meta data in the seurat object. This info is important to integrate with my data. Thanks!
> 
> I keep it in the Seurat object, and I'm also uploading the processed .gem file.

@yangmean Can you provide an update on the progress of this upload? Thanks!

**Comment by yangmean** [comment]
@liuyifang @sarahshuang Hello, I have completed the data uploading, finally. I am so sorry for the extended delay, and you can now download the data through the GEO database using the GSE250503 accession number.

**Comment by liuyifang** [comment]
@yangmean Thanks!

**Comment by sarahshuang** [comment]
@yangmean Thanks! Sorry to bother you again, buy I only found ssDNA image there. Are the full H&E staining in Figure S3A available?
