### ISSUE TITLE
how to get H&E image?

### ISSUE THREAD

**Issue by sarahshuang** [yangmean/Spatiotemperal_mouse_implation_sites#2]
Thanks so much for your reply to my last issue. 

Sorry to bother you again, but I only found the ssDNA image through the GEO database using the GSE250503 accession number. Are the full H&E staining images in Figure S2A or S3A available? I want to learn more about the DSC morphologies in the antimesometrium, but I only found an enlarged one there   :(

<img width="1163" alt="截屏2024-01-02 15 19 28" src="https://github.com/yangmean/Spatiotemporal_mouse_implantation_sites/assets/105658106/fcc687d4-e9cf-49cc-8995-cbc58c586204">

<img width="782" alt="截屏2024-01-02 15 16 44" src="https://github.com/yangmean/Spatiotemporal_mouse_implantation_sites/assets/105658106/08fb1c4d-fe0a-4e56-b009-f40c1aa47db8">

**Comment by yangmean** [comment]
I will ask my collaborator for the high resolution pictures. But I remember that even the raw H&E staining pictures do not have a high resolution.

**Comment by sarahshuang** [comment]
Okay. Thank you so much!

**Comment by sarahshuang** [comment]
Hi yang,

How's it going now? Are pictures available?

**Comment by yangmean** [comment]
@sarahshuang Hi Sarah, Sorry for the late reply. You can download the H&E data from GEO (GSE250503) now. The H&E files are compressed, and ended with "tar.gz" for each sample. Additionally,  these images can be opened with CaseViewer. If you have any questions, please let me know.

**Comment by sarahshuang** [comment]
@yangmean I have downloaded and viewed them successfully. Thank you so much!!!
